### ISSUE TITLE
dataparser type of GS2GS

### ISSUE THREAD

**Issue by Harr7y** [cvachha/instruct-gs2gs#2]
The dataparser type of igs2gs_datamanager.py is **NerfstudioDataParserConfig**.
# https://github.com/cvachha/instruct-gs2gs/blob/fa32e20d1df90b179f4ad645f57a2d3978b94368/igs2gs/igs2gs_datamanager.py#L91

While it is **ColmapDataParserConfig** of igs2gs_config.py.
# https://github.com/cvachha/instruct-gs2gs/blob/fa32e20d1df90b179f4ad645f57a2d3978b94368/igs2gs/igs2gs_config.py#L50

I wonder which one was used in the end? I think it's **ColmapDataParserConfig**. 
When I try to switch the dataparser of igs2gs_config.py to **NerfstudioDataParserConfig**, and reconduct the `pip install -e .`.
An error occured without any information, can you tell me how to change the dataparser of gaussian splatting to the **NerfstudioDataParserConfig**?

**Comment by cvachha** [comment]
Nerfstudio's gaussian splatting previously required the colmap dataparser to obtain the point cloud initialization, but in the most recent Nerfstudio 1.0 release, I believe splatting is now also supported with the NerfstudioDataParser. I will update this repo soon with other necessary changes for compatibility with Nerfstudio 1.0.

**Comment by Harr7y** [comment]
Thanks a lot. So in this GS2GS repo, the DataParser is still ColmapDataParserConfig, right?

**Comment by cvachha** [comment]
I just pushed some updates for compatibility with Nerfstudio V1.0, including replacing the ColmapDataparser with the NerfstudioDataParser. Now non colmap datasets like polycam should also work. Let me know if you run into any errors.

**Comment by Harr7y** [comment]
Thanks for your contributions, it works now. :grinning:
