### ISSUE TITLE
FileNotFoundError when I first run igs2gs 

### ISSUE THREAD

**Issue by yukyeongmin** [cvachha/instruct-gs2gs#3]
I installed igs2gs by cloning repo. When i tried to run igs2gs after training splafacto, I met FileNotFoundError.

`  File "nerfstudio/instruct-gs2gs/igs2gs/igs2gs_pipeline.py", line 122, in get_train_loss_dict
    plt.imsave("testing_seq_edits/original_image_"+str(idx)+".jpg", original_image.squeeze().permute(1, 2, 0).detach().cpu().numpy())
  File "anaconda3/envs/nerfstudio/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2200, in imsave
    return matplotlib.image.imsave(fname, arr, **kwargs)
  File "anaconda3/envs/nerfstudio/lib/python3.8/site-packages/matplotlib/image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "anaconda3/envs/nerfstudio/lib/python3.8/site-packages/PIL/Image.py", line 2436, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'testing_seq_edits/original_image_0.jpg'
`

I added `os.path.exists("testing_seq_edits") or os.makedirs("testing_seq_edits")` just before line 122 to fix. 
But it seems not perfect cause every igs2gs share this folder so i cannot run multiple model at once.

**Comment by cvachha** [comment]
Thanks for letting us know. I have removed the image saving lines from igs2gs_pipeline.py
