### ISSUE TITLE
Regarding using LPIPS loss

### ISSUE THREAD

**Issue by yt2639** [cvachha/instruct-gs2gs#5]
Hi authors, thanks for sharing the code. In the paper, you mentioned that you used LPIPS and L1 loss for training igs2gs. However, here in the code,

https://github.com/cvachha/instruct-gs2gs/blob/a5d43294b9b8e4db5395e3df13cac78625abfee8/igs2gs/igs2gs.py#L51C5-L51C8

it seems like the model does not overwrite the original get_loss_dict function and therefore it still uses SSIM loss and L1 loss. Is this intended?

Thanks!

**Comment by ayaanzhaque** [comment]
This was a mistake on our part in the paper, whatever is in the code is correct. So we do not use LPIPS loss.
