### ISSUE TITLE
Connection error instruct-pix2pix

### ISSUE THREAD

**Issue by 2629630207** [cvachha/instruct-gs2gs#7]
I use [ns-train igs2gs --data ./poster --load-dir ./outputs/poster/nerfacto/2024-02-20_172727/nerfstudio_models  --pipeline.prompt "a chair" --pipeline.guidance-scale 12.5 --pipeline.image-guidance-scale 1.5 ]
and the error is 
![~N$2`OP_PWAVF$30@HW{U9N](https://github.com/cvachha/instruct-gs2gs/assets/55966964/f2b8b1a6-8f2c-42a1-97ae-78d962166500)
I konw there is something wrong with my net, so it means that I should pre-install instruct-pix2pix from https://huggingface.co/timbrooks/instruct-pix2pix to avoid this?

**Comment by ayaanzhaque** [comment]
Ya maybe. Seems like some huggingface issue, so maybe search on those forums to find a solution.

**Comment by 2629630207** [comment]
> Ya maybe. Seems like some huggingface issue, so maybe search on those forums to find a solution.

Thank you for your suggestion. I download pix2pix,v1-4 and v1-5 and it runs. However, another error occurs when loading the checkpoints.
![UJ12}XNHMR416QLFQ{T{U80](https://github.com/cvachha/instruct-gs2gs/assets/55966964/e3f33e7b-a9c0-4e78-92ef-7561563ef050)
Could you please offer me some advice?

**Comment by ayaanzhaque** [comment]
Seems like some weird issue with loading the pre-trained GS. @cvachha any ideas here?

**Comment by cvachha** [comment]
Hi, @2629630207 I'm not exactly sure why this issue is occurring. If the GS you are editing was trained before the Nerfstudio V1,0 release, that might cause this issue. I would recommend to try re-training the initial GS with splatfacto and then running igs2gs, but I'm not sure why loading a checkpoint is giving this error. 
If you load a splatfacto checkpoint with ns-train splatfacto (without running igs2gs) does this error still occur?

**Comment by 2629630207** [comment]
> Hi, @2629630207 I'm not exactly sure why this issue is occurring. If the GS you are editing was trained before the Nerfstudio V1,0 release, that might cause this issue. I would recommend to try re-training the initial GS with splatfacto and then running igs2gs, but I'm not sure why loading a checkpoint is giving this error. If you load a splatfacto checkpoint with ns-train splatfacto (without running igs2gs) does this error still occur?

Thank you for your reply.I try splatfacto and runn igs2gs, it works.
![20240223101810](https://github.com/cvachha/instruct-gs2gs/assets/55966964/1bab08fa-569e-49da-ab91-121a1a466300)

So I believe it's likely a version issue of Nerfstudio as you say. I will check the version.
Expressing my gratitude once again.

**Comment by cici19850** [comment]
I have encountered the same problem as you. How did you solve it? thank you
